# Generated by Django 4.1.5 on 2023-08-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(blank=True, default='On Hold', max_length=100),
        ),
    ]
