# Generated by Django 4.1.5 on 2023-08-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_doctor_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('symptom', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=100)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('profile', models.ImageField(upload_to='doc_profile/')),
                ('status', models.CharField(blank=True, default='Out Patient', max_length=100)),
                ('join_date', models.DateTimeField(auto_now=True, verbose_name='Created')),
            ],
        ),
    ]
