# Generated by Django 4.1.5 on 2023-08-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='op_num',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
