# Generated by Django 4.1.5 on 2023-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_patient_op_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doc_dep',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
