# Generated by Django 4.1.5 on 2023-08-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0007_patient_doc_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, default='On Hold', max_length=100),
        ),
    ]
