# Generated by Django 4.1.5 on 2023-09-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_alter_patient_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=10000)),
                ('d_d', models.CharField(blank=True, max_length=200)),
                ('join_date', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('status', models.CharField(blank=True, default='Processing', max_length=100)),
            ],
        ),
    ]
