# Generated by Django 4.1.5 on 2023-09-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0009_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
