# Generated by Django 4.1.5 on 2023-09-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0010_appointment_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user_name',
            new_name='patient_name',
        ),
    ]
