# Generated by Django 4.1.5 on 2023-09-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0011_rename_user_name_appointment_patient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='d_d',
            new_name='doctor_name',
        ),
    ]
