# Generated by Django 4.1.5 on 2023-09-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0012_rename_d_d_appointment_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_user_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_user_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
