# Generated by Django 4.1.5 on 2023-09-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0014_discharge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='discharge',
            new_name='discharge_tb',
        ),
    ]
