# Generated by Django 4.1.5 on 2023-09-07 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0015_rename_discharge_discharge_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharge_tb',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospitalapp.patient'),
        ),
    ]
