# Generated by Django 4.1.5 on 2023-09-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0018_discharge_tb_doctor_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge_tb',
            name='room_charge',
            field=models.IntegerField(default=0),
        ),
    ]
