# Generated by Django 4.1.5 on 2023-09-15 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0020_discharge_tb_doc_fee_discharge_tb_medicine_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='app_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
