# Generated by Django 4.1.5 on 2023-09-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0021_appointment_app_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
