# Generated by Django 4.1.5 on 2023-09-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0023_remove_doctor_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='op_num',
            new_name='pat_id',
        ),
    ]
