# Generated by Django 4.1.5 on 2023-09-27 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0024_rename_op_num_patient_pat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='app_p_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.patient'),
        ),
    ]
