# Generated by Django 4.1.5 on 2023-09-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0025_appointment_app_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='app_p_id',
        ),
    ]
