# Generated by Django 4.1.5 on 2023-09-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0026_remove_appointment_app_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='bill_status',
            field=models.CharField(blank=True, default='On_Hold', max_length=100),
        ),
    ]
