# Generated by Django 4.1.5 on 2023-10-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0027_appointment_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
